### ISSUE TITLE
Outbound call after long call leads to core dump

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#1175]
Fedora 33 with:
  * baresip 1.0.0 (unpatched)
  * libre 1.1.0 (unpatched)
  * librem 0.6.0 (up to commit 52bbacb, otherwise unpatched)

PBX: AVM FRITZ!Box

1. Begin of outbound call using baresip (timeline: 0:00)
2. Inbound ringing during existing call, was picked up at another other phone (timeline: ?:??, not sure if it's even relevant)
3. Caller ended outbound call regulary (timeline: 0:35)
4. Try of next outbound call using baresip (timeline: 0:47)
5. Crash with core dump (timeline: 0:47)

```
[New LWP 1381244]
[New LWP 1356117]
[New LWP 1356114]
[New LWP 1356115]
[New LWP 1356116]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `baresip'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:49
49	  return ret;
[Current thread is 1 (Thread 0x7f540224e640 (LWP 1381244))]

Thread 1 (Thread 0x7f540224e640 (LWP 1381244)):
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f5417c608a4 in __GI_abort () at abort.c:79
#2  0x00007f5417cb9f27 in __libc_message (action=<optimized out>, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f5417cc1c1c in malloc_printerr (str=str@entry=0x7f5417dcec00 "malloc(): unaligned fastbin chunk detected") at malloc.c:5389
#4  0x00007f5417cc4d01 in _int_malloc (av=av@entry=0x7f53f0000020, bytes=bytes@entry=64) at malloc.c:3615
#5  0x00007f5417cc7475 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3448
#6  0x00007f5416da6893 in pa_xmalloc0 (size=<optimized out>) at pulse/xmalloc.c:74
#7  0x00007f5416d1d8e1 in _pa_xnew0_internal (n=1, k=64) at ./pulse/xmalloc.h:75
#8  pa_iochannel_new (m=0x55bd52fd0dc8, ifd=28, ofd=28) at pulsecore/iochannel.c:168
#9  0x00007f5416d380be in do_call (c=0x55bd5300ab10) at pulsecore/socket-client.c:150
#10 0x00007f5416d976b0 in dispatch_defer (m=0x55bd52fd0d70) at pulse/mainloop.c:680
#11 pa_mainloop_dispatch (m=m@entry=0x55bd52fd0d70) at pulse/mainloop.c:887
#12 0x00007f5416d97c52 in pa_mainloop_iterate (m=m@entry=0x55bd52fd0d70, block=block@entry=1, retval=retval@entry=0x0) at pulse/mainloop.c:927
#13 0x00007f5416d97cf0 in pa_mainloop_run (m=0x55bd52fd0d70, retval=0x0) at pulse/mainloop.c:942
#14 0x00007f5416da7efd in thread (userdata=0x55bd52fc2900) at pulse/thread-mainloop.c:101
#15 0x00007f5416d4323c in internal_thread_func (userdata=0x55bd53024370) at pulsecore/thread-posix.c:81
#16 0x00007f5417f673f9 in start_thread (arg=0x7f540224e640) at pthread_create.c:463
#17 0x00007f5417d3b903 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f5402acf640 (LWP 1356117)):
#0  0x00007f5417d3080f in __GI___poll (fds=0x7f54100cafc0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f5415d116f6 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7f54100cafc0, timeout=<optimized out>, context=0x7f54100c8a20) at ../glib/gmain.c:4422
#2  g_main_context_iterate.constprop.0 (context=0x7f54100c8a20, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4114
#3  0x00007f5415cbf033 in g_main_loop_run (loop=0x7f54100c8b10) at ../glib/gmain.c:4317
#4  0x00007f5415f07d1a in gdbus_shared_thread_func (user_data=0x7f54100c89f0) at ../gio/gdbusprivate.c:280
#5  0x00007f5415ced2b2 in g_thread_proxy (data=0x7f54100b9760) at ../glib/gthread.c:820
#6  0x00007f5417f673f9 in start_thread (arg=0x7f5402acf640) at pthread_create.c:463
#7  0x00007f5417d3b903 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f541788d080 (LWP 1356114)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x55bd52ffcd78) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55bd52fd0e70, cond=0x55bd52ffcd50) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55bd52ffcd50, mutex=0x55bd52fd0e70) at pthread_cond_wait.c:638
#3  0x00007f5416da4eac in pa_threaded_mainloop_wait (m=0x55bd52fc2900) at pulse/thread-mainloop.c:216
#4  0x00007f5416dc7be4 in pa_simple_new (server=0x0, name=0x7f54180062d1 "Baresip", dir=PA_STREAM_PLAYBACK, dev=0x0, stream_name=0x7f54180062c3 "VoIP Playback", ss=0x7ffd2a8a4284, map=0x0, attr=0x7ffd2a8a4290, rerror=0x7ffd2a8a4280) at pulse/simple.c:192
#5  0x00007f5418005562 in pulse_player_alloc (stp=0x55bd52fd9930, ap=0x7ffd2a8a4284, prm=0x7ffd2a8a42f0, device=<optimized out>, wh=0x55bd51a83e00 <auplay_write_handler>, arg=0x55bd52fd9930) at modules/pulse/player.c:129
#6  0x000055bd51a8d654 in auplay_alloc (arg=0x55bd52fd9930, wh=0x55bd51a83e00 <auplay_write_handler>, device=0x55bd52faaf20 "", prm=0x7ffd2a8a42f0, name=<optimized out>, auplayl=0x55bd51ab0988 <baresip.lto_priv+104>, stp=0x55bd52fd9930) at src/auplay.c:109
#7  start_player (auplayl=0x55bd51ab0988 <baresip.lto_priv+104>, a=0x55bd52fd9620, rx=0x55bd52fd9930) at src/audio.c:1480
#8  audio_start (a=0x55bd52fd9620) at src/audio.c:1639
#9  audio_start (a=0x55bd52fd9620) at src/audio.c:1621
#10 0x000055bd51a8dbef in audio_decoder_set (a=<optimized out>, ac=ac@entry=0x7f5418020000 <g722>, pt_rx=<optimized out>, params=<optimized out>) at src/audio.c:1859
#11 0x000055bd51a9033b in audio_decoder_set (params=<optimized out>, pt_rx=<optimized out>, ac=0x7f5418020000 <g722>, a=<optimized out>) at src/audio.c:1813
#12 update_audio (call=0x55bd53000ee0) at src/call.c:334
#13 update_media (call=0x55bd53000ee0) at src/call.c:414
#14 0x00007f5417fa5d78 in invite_resp_handler (err=0, msg=0x55bd52fed040, arg=0x55bd53027a50) at src/sipsess/connect.c:47
#15 0x00007f5417f9f141 in invite_response (msg=0x55bd52fed040, ct=0x55bd52fdd730) at src/sip/ctrans.c:227
#16 response_handler (msg=0x55bd52fed040, arg=<optimized out>) at src/sip/ctrans.c:276
#17 0x00007f5417fa323f in sip_recv (sip=0x55bd52f8ab20, msg=0x55bd52fed040, start=<optimized out>) at src/sip/transp.c:291
#18 0x00007f5417fa33d5 in udp_recv_handler (src=0x7ffd2a8a4450, mb=<optimized out>, arg=0x55bd52f8dd40) at src/sip/transp.c:364
#19 0x00007f5417fc648e in udp_read (us=0x55bd52f8ddd0, fd=10) at src/udp/udp.c:219
#20 0x00007f5417fd527c in fd_poll (re=re@entry=0x7f5417ffd080 <global_re>) at src/main/main.c:896
#21 0x00007f5417fd5c00 in re_main (signalh=0x55bd51a9a370 <signal_handler>) at src/main/main.c:1030
#22 0x000055bd51a83554 in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:301

Thread 4 (Thread 0x7f5415383640 (LWP 1356115)):
#0  0x00007f5417d3080f in __GI___poll (fds=0x7f54100f5ac0, nfds=2, timeout=11) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f5415d116f6 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7f54100f5ac0, timeout=<optimized out>, context=0x7f54100502d0) at ../glib/gmain.c:4422
#2  g_main_context_iterate.constprop.0 (context=0x7f54100502d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4114
#3  0x00007f5415cbf033 in g_main_loop_run (loop=0x7f54100f5c30) at ../glib/gmain.c:4317
#4  0x00007f54161e429a in IA__gtk_main () at gtkmain.c:1270
#5  0x00007f541656dc08 in gtk_thread (arg=0x7f5416574120 <mod_obj>) at modules/gtk/gtk_mod.c:859
#6  0x00007f5417f673f9 in start_thread (arg=0x7f5415383640) at pthread_create.c:463
#7  0x00007f5417d3b903 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f5414aae640 (LWP 1356116)):
#0  0x00007f5417d3080f in __GI___poll (fds=0x7f54100b9d30, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f5415d116f6 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7f54100b9d30, timeout=<optimized out>, context=0x7f54100bb650) at ../glib/gmain.c:4422
#2  g_main_context_iterate.constprop.0 (context=context@entry=0x7f54100bb650, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4114
#3  0x00007f5415cbcd43 in g_main_context_iteration (context=0x7f54100bb650, may_block=may_block@entry=1) at ../glib/gmain.c:4184
#4  0x00007f5415cbe961 in glib_worker_main (data=<optimized out>) at ../glib/gmain.c:6077
#5  0x00007f5415ced2b2 in g_thread_proxy (data=0x7f5410085f60) at ../glib/gthread.c:820
#6  0x00007f5417f673f9 in start_thread (arg=0x7f5414aae640) at pthread_create.c:463
#7  0x00007f5417d3b903 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

From                To                  Syms Read   Shared Object Library
0x00007f5417f97150  0x00007f5417fde546  Yes         /lib64/libre.so.0
0x00007f5417f65a90  0x00007f5417f74125  Yes         /lib64/libpthread.so.0
0x00007f5417f4e5f0  0x00007f5417f5577f  Yes         /lib64/librem.so.0
0x00007f5417e143d0  0x00007f5417eaf718  Yes         /lib64/libm.so.6
0x00007f5417c60690  0x00007f5417dad69d  Yes         /lib64/libc.so.6
0x00007f5417c35270  0x00007f5417c361c9  Yes         /lib64/libdl.so.2
0x00007f5417bb58f0  0x00007f5417c09f16  Yes         /lib64/libssl.so.1.1
0x00007f5417924000  0x00007f5417acfe50  Yes         /lib64/libcrypto.so.1.1
0x00007f54178915f0  0x00007f541789eb2b  Yes         /lib64/libz.so.1
0x00007f5418022090  0x00007f5418042f96  Yes         /lib64/ld-linux-x86-64.so.2
0x00007f5417881570  0x00007f5417887e81  Yes         /lib64/libnss_sss.so.2
0x00007f541801d0d0  0x00007f541801d3a7  Yes         /usr/lib64/baresip/modules/g722.so
0x00007f5416ed95a0  0x00007f5416f30d8a  Yes         /lib64/libspandsp.so.2
0x00007f5416e4fa00  0x00007f5416e920a0  Yes         /lib64/libjpeg.so.62
0x00007f5416dd4e00  0x00007f5416e16290  Yes         /lib64/libtiff.so.5
0x00007f541800f2d0  0x00007f5418015f49  Yes         /lib64/libjbig.so.2.1
0x00007f541800a070  0x00007f541800a3c3  Yes         /usr/lib64/baresip/modules/g711.so
0x00007f54180052e0  0x00007f5418005f2e  Yes         /usr/lib64/baresip/modules/pulse.so
0x00007f5416dc7610  0x00007f5416dc8848  Yes         /lib64/libpulse-simple.so.0
0x00007f5416d7df30  0x00007f5416dab9a0  Yes         /lib64/libpulse.so.0
0x00007f5416d00df0  0x00007f5416d45342  Yes         /usr/lib64/pulseaudio/libpulsecommon-14.0.so
0x00007f5416ce3050  0x00007f5416ce312f  Yes         /lib64/libX11-xcb.so.1
0x00007f5416bbc370  0x00007f5416c4679c  Yes         /lib64/libX11.so.6
0x00007f5416b7d6e0  0x00007f5416b8fb06  Yes         /lib64/libxcb.so.1
0x00007f5416b598c0  0x00007f5416b66e59  Yes         /lib64/libICE.so.6
0x00007f5416b4b270  0x00007f5416b4f345  Yes         /lib64/libSM.so.6
0x00007f5416b421f0  0x00007f5416b44b8c  Yes         /lib64/libXtst.so.6
0x00007f5416a95530  0x00007f5416b0fd74  Yes         /lib64/libsystemd.so.0
0x00007f5416a15860  0x00007f5416a5ece4  Yes         /lib64/libsndfile.so.1
0x00007f5416a08250  0x00007f5416a0a7e8  Yes         /lib64/libasyncns.so.0
0x00007f54169c3d90  0x00007f54169ef642  Yes         /lib64/libdbus-1.so.3
0x00007f54169b03f0  0x00007f54169b1f0a  Yes         /lib64/libcap.so.2
0x00007f54169a6770  0x00007f54169a9a60  Yes         /lib64/librt.so.1
0x00007f541699f200  0x00007f541699ff22  Yes         /lib64/libXau.so.6
0x00007f5416997310  0x00007f541699a967  Yes         /lib64/libuuid.so.1
0x00007f54169843d0  0x00007f541698e53e  Yes         /lib64/libXext.so.6
0x00007f5416970270  0x00007f541697a9a7  Yes         /lib64/libXi.so.6
0x00007f5416945510  0x00007f541695f04a  Yes         /lib64/liblzma.so.5
0x00007f541687bda0  0x00007f541692d6d0  Yes         /lib64/libzstd.so.1
0x00007f54168514d0  0x00007f5416867ad9  Yes         /lib64/liblz4.so.1
0x00007f5416736b40  0x00007f541680da50  Yes         /lib64/libgcrypt.so.20
0x00007f54167125f0  0x00007f5416723195  Yes         /lib64/libgcc_s.so.1
0x00007f54167021d0  0x00007f541670a9b7  Yes         /lib64/libgsm.so.1
0x00007f54166ae8d0  0x00007f54166f3e59  Yes         /lib64/libFLAC.so.8
0x00007f541669c260  0x00007f541669e555  Yes         /lib64/libogg.so.0
0x00007f541666f5f0  0x00007f5416686081  Yes         /lib64/libvorbis.so.0
0x00007f54165d40b0  0x00007f54165d66b6  Yes         /lib64/libvorbisenc.so.2
0x00007f54165aa730  0x00007f54165b769c  Yes         /lib64/libresolv.so.2
0x00007f5416585a50  0x00007f5416599d02  Yes         /lib64/libgpg-error.so.0
0x00007f5416fa0130  0x00007f5416fa06e7  Yes         /usr/lib64/baresip/modules/stun.so
0x00007f5416f9b170  0x00007f5416f9b897  Yes         /usr/lib64/baresip/modules/turn.so
0x00007f5416f944d0  0x00007f5416f95ed8  Yes         /usr/lib64/baresip/modules/ice.so
0x00007f5416f8e270  0x00007f5416f8ed0c  Yes         /usr/lib64/baresip/modules/auloop.so
0x00007f541657d2a0  0x00007f541657dd54  Yes         /usr/lib64/baresip/modules/contact.so
0x00007f5416577270  0x00007f541657788f  Yes         /usr/lib64/baresip/modules/debug_cmd.so
0x00007f541656cc70  0x00007f54165702ce  Yes         /usr/lib64/baresip/modules/gtk.so
0x00007f54160ff8d0  0x00007f54163bd999  Yes         /lib64/libgtk-x11-2.0.so.0
0x00007f5415fe4700  0x00007f54160519e3  Yes         /lib64/libgdk-x11-2.0.so.0
0x00007f5415e36350  0x00007f5415f38e1c  Yes         /lib64/libgio-2.0.so.0
0x00007f5415daceb0  0x00007f5415ddb778  Yes         /lib64/libgobject-2.0.so.0
0x00007f5415c89b30  0x00007f5415d12112  Yes         /lib64/libglib-2.0.so.0
0x00007f5415c67450  0x00007f5415c68323  Yes         /lib64/libgmodule-2.0.so.0
0x00007f5415c5a630  0x00007f5415c606fd  Yes         /lib64/libpangocairo-1.0.so.0
0x00007f5415c4d1c0  0x00007f5415c4f546  Yes         /lib64/libXfixes.so.3
0x00007f5415c2cd70  0x00007f5415c3ac84  Yes         /lib64/libatk-1.0.so.0
0x00007f5415b19600  0x00007f5415be728f  Yes         /lib64/libcairo.so.2
0x00007f5415ae4d10  0x00007f5415afa431  Yes         /lib64/libgdk_pixbuf-2.0.so.0
0x00007f5415acb030  0x00007f5415ad4a3a  Yes         /lib64/libpangoft2-1.0.so.0
0x00007f5415a7f910  0x00007f5415aa5d04  Yes         /lib64/libpango-1.0.so.0
0x00007f5415a2c780  0x00007f5415a559ae  Yes         /lib64/libfontconfig.so.1
0x00007f5415a1a270  0x00007f5415a20502  Yes         /lib64/libXrender.so.1
0x00007f5415a14110  0x00007f5415a14a71  Yes         /lib64/libXinerama.so.1
0x00007f5415a08220  0x00007f5415a0ecc5  Yes         /lib64/libXrandr.so.2
0x00007f54159fc5f0  0x00007f5415a010fc  Yes         /lib64/libXcursor.so.1
0x00007f54159f50d0  0x00007f54159f5b05  Yes         /lib64/libXcomposite.so.1
0x00007f54159f0100  0x00007f54159f0a6b  Yes         /lib64/libXdamage.so.1
0x00007f54159b75e0  0x00007f54159df342  Yes         /lib64/libmount.so.1
0x00007f5415988b50  0x00007f54159a0e2d  Yes         /lib64/libselinux.so.1
0x00007f54159772c0  0x00007f541597bd6c  Yes         /lib64/libffi.so.6
0x00007f54158fe1f0  0x00007f541595356a  Yes         /lib64/libpcre.so.1
0x00007f541585aab0  0x00007f54158e03bf  Yes         /lib64/libpixman-1.so.0
0x00007f5415799a40  0x00007f541581c2bc  Yes         /lib64/libfreetype.so.6
0x00007f5415758940  0x00007f541577f3a9  Yes         /lib64/libpng16.so.16
0x00007f541574f090  0x00007f541574fb73  Yes         /lib64/libxcb-shm.so.0
0x00007f5415744230  0x00007f5415748c3e  Yes         /lib64/libxcb-render.so.0
0x00007f541567ae80  0x00007f541570a982  Yes         /lib64/libharfbuzz.so.0
0x00007f54156552f0  0x00007f54156593ee  Yes         /lib64/libfribidi.so.0
0x00007f541564a2a0  0x00007f541564da53  Yes         /lib64/libthai.so.0
0x00007f54154ec9b0  0x00007f54155f0d2a  Yes         /lib64/libxml2.so.2
0x00007f5415490a10  0x00007f54154ad1b2  Yes         /lib64/libblkid.so.1
0x00007f54153f44b0  0x00007f541545d9af  Yes         /lib64/libpcre2-8.so.0
0x00007f54153e1550  0x00007f54153ed966  Yes         /lib64/libbz2.so.1
0x00007f54153d20e0  0x00007f54153d9036  Yes         /lib64/libbrotlidec.so.1
0x00007f54153b3190  0x00007f54153c97fd  Yes         /lib64/libgraphite2.so.3
0x00007f54153a9240  0x00007f54153ac12b  Yes         /lib64/libdatrie.so.1
0x00007f5415385060  0x00007f5415385585  Yes         /lib64/libbrotlicommon.so.1
0x00007f54165606a0  0x00007f5416562a3d  Yes         /usr/lib64/baresip/modules/menu.so
0x00007f5416549320  0x00007f541654a9d2  Yes         /usr/lib64/baresip/modules/vidloop.so
0x00007f5414b5a260  0x00007f5414b5a9c9  Yes         /usr/lib64/gtk-2.0/2.10.0/engines/libadwaita.so
0x00007f5414b4d460  0x00007f5414b52881  Yes         /usr/lib64/gtk-2.0/2.10.0/engines/libpixmap.so
0x00007f5414b434f0  0x00007f5414b45850  Yes         /usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
0x00007f5414b1b430  0x00007f5414b1ca1e  Yes         /lib64/libcanberra-gtk.so.0
0x00007f5414b15090  0x00007f5414b151d2  Yes         /lib64/libgthread-2.0.so.0
0x00007f5414b04700  0x00007f5414b0dac5  Yes         /lib64/libcanberra.so.0
0x00007f5414af8440  0x00007f5414afc93c  Yes         /lib64/libvorbisfile.so.3
0x00007f5414ae1510  0x00007f5414aedd15  Yes         /lib64/libtdb.so.1
0x00007f5414ad38d0  0x00007f5414ad7b46  Yes         /lib64/libltdl.so.7
0x00007f5414277e60  0x00007f541429110b  Yes         /usr/lib64/gio/modules/libgvfsdbus.so
0x00007f541423e7e0  0x00007f5414256ce8  Yes         /usr/lib64/gvfs/libgvfscommon.so
$1 = 0x7f5414103000 ""
$2 = 0x0
rax            0x0                 0
rbx            0x7f540224e640      139998789953088
rcx            0x7f5417c779d5      139999152929237
rdx            0x0                 0
rsi            0x7f540224d700      139998789949184
rdi            0x2                 2
rbp            0x7f540224da50      0x7f540224da50
rsp            0x7f540224d700      0x7f540224d700
r8             0x0                 0
r9             0x7f540224d700      139998789949184
r10            0x8                 8
r11            0x246               582
r12            0x1000              4096
r13            0x7f540224d970      139998789949808
r14            0x10                16
r15            0x7f5414103000      139999090585600
rip            0x7f5417c779d5      0x7f5417c779d5 <__GI_raise+325>
eflags         0x246               [ PF ZF IF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
Dump of assembler code for function __GI_raise:
   0x00007f5417c77890 <+0>:	endbr64 
   0x00007f5417c77894 <+4>:	sub    $0x118,%rsp
   0x00007f5417c7789b <+11>:	mov    %edi,%r8d
   0x00007f5417c7789e <+14>:	mov    $0x8,%r10d
   0x00007f5417c778a4 <+20>:	xor    %edi,%edi
   0x00007f5417c778a6 <+22>:	mov    %fs:0x28,%rax
   0x00007f5417c778af <+31>:	mov    %rax,0x108(%rsp)
   0x00007f5417c778b7 <+39>:	xor    %eax,%eax
   0x00007f5417c778b9 <+41>:	mov    %rsp,%r9
   0x00007f5417c778bc <+44>:	lea    0x80(%rsp),%rsi
   0x00007f5417c778c4 <+52>:	movabs $0xfffffffe7fffffff,%rax
   0x00007f5417c778ce <+62>:	mov    %rax,0x80(%rsp)
   0x00007f5417c778d6 <+70>:	mov    %r9,%rdx
   0x00007f5417c778d9 <+73>:	mov    $0xe,%eax
   0x00007f5417c778de <+78>:	movq   $0xffffffffffffffff,0x88(%rsp)
   0x00007f5417c778ea <+90>:	movq   $0xffffffffffffffff,0x90(%rsp)
   0x00007f5417c778f6 <+102>:	movq   $0xffffffffffffffff,0x98(%rsp)
   0x00007f5417c77902 <+114>:	movq   $0xffffffffffffffff,0xa0(%rsp)
   0x00007f5417c7790e <+126>:	movq   $0xffffffffffffffff,0xa8(%rsp)
   0x00007f5417c7791a <+138>:	movq   $0xffffffffffffffff,0xb0(%rsp)
   0x00007f5417c77926 <+150>:	movq   $0xffffffffffffffff,0xb8(%rsp)
   0x00007f5417c77932 <+162>:	movq   $0xffffffffffffffff,0xc0(%rsp)
   0x00007f5417c7793e <+174>:	movq   $0xffffffffffffffff,0xc8(%rsp)
   0x00007f5417c7794a <+186>:	movq   $0xffffffffffffffff,0xd0(%rsp)
   0x00007f5417c77956 <+198>:	movq   $0xffffffffffffffff,0xd8(%rsp)
   0x00007f5417c77962 <+210>:	movq   $0xffffffffffffffff,0xe0(%rsp)
   0x00007f5417c7796e <+222>:	movq   $0xffffffffffffffff,0xe8(%rsp)
   0x00007f5417c7797a <+234>:	movq   $0xffffffffffffffff,0xf0(%rsp)
   0x00007f5417c77986 <+246>:	movq   $0xffffffffffffffff,0xf8(%rsp)
   0x00007f5417c77992 <+258>:	syscall 
   0x00007f5417c77994 <+260>:	mov    $0x27,%ecx
   0x00007f5417c77999 <+265>:	mov    %ecx,%eax
   0x00007f5417c7799b <+267>:	syscall 
   0x00007f5417c7799d <+269>:	mov    %rax,%rdi
   0x00007f5417c779a0 <+272>:	mov    $0xba,%eax
   0x00007f5417c779a5 <+277>:	syscall 
   0x00007f5417c779a7 <+279>:	mov    %eax,%esi
   0x00007f5417c779a9 <+281>:	mov    %r8d,%edx
   0x00007f5417c779ac <+284>:	mov    $0xea,%eax
   0x00007f5417c779b1 <+289>:	syscall 
   0x00007f5417c779b3 <+291>:	cmp    $0xfffffffffffff000,%rax
   0x00007f5417c779b9 <+297>:	ja     0x7f5417c779f8 <__GI_raise+360>
   0x00007f5417c779bb <+299>:	mov    %eax,%r8d
   0x00007f5417c779be <+302>:	mov    $0x8,%r10d
   0x00007f5417c779c4 <+308>:	xor    %edx,%edx
   0x00007f5417c779c6 <+310>:	mov    %r9,%rsi
   0x00007f5417c779c9 <+313>:	mov    $0x2,%edi
   0x00007f5417c779ce <+318>:	mov    $0xe,%eax
   0x00007f5417c779d3 <+323>:	syscall 
=> 0x00007f5417c779d5 <+325>:	mov    0x108(%rsp),%rax
   0x00007f5417c779dd <+333>:	sub    %fs:0x28,%rax
   0x00007f5417c779e6 <+342>:	jne    0x7f5417c77a0c <__GI_raise+380>
   0x00007f5417c779e8 <+344>:	mov    %r8d,%eax
   0x00007f5417c779eb <+347>:	add    $0x118,%rsp
   0x00007f5417c779f2 <+354>:	ret    
   0x00007f5417c779f3 <+355>:	nopl   0x0(%rax,%rax,1)
   0x00007f5417c779f8 <+360>:	mov    0x186459(%rip),%rdx        # 0x7f5417dfde58
   0x00007f5417c779ff <+367>:	neg    %eax
   0x00007f5417c77a01 <+369>:	mov    $0xffffffff,%r8d
   0x00007f5417c77a07 <+375>:	mov    %eax,%fs:(%rdx)
   0x00007f5417c77a0a <+378>:	jmp    0x7f5417c779be <__GI_raise+302>
   0x00007f5417c77a0c <+380>:	call   0x7f5417d4b230 <__stack_chk_fail>
End of assembler dump.
```

Originally reported at [Red Hat Bugzilla, Bug #1911725](https://bugzilla.redhat.com/show_bug.cgi?id=1911725), but auto-private due to confidential data contained in the auto-gathered logs. If you need more details, please let me know…but given some of them contain at least phone numbers, I can't simply post them in public.

**Comment by alfredh** [comment]
hi, some ideas:

1. check if the crash happens all the time, or only occationally

2. find out which audio driver is used.

3. can you also share config and log ?

4. the crash happens inside the pulse thread:

```
malloc(): unaligned fastbin chunk detected
```

perhaps take a look at pulse source code and find out what it means

**Comment by alfredh** [comment]
running baresip with valgrind can also help to find out if there is any data corruption.

is there anyone using pulseaudio that can test with valgrind ?

**Comment by alfredh** [comment]
we need more information to solve this bug, since no-one has replied I will close it.
Please feel free to re-open if you can provide the required info.
