### ISSUE TITLE
Baresip hangs when call is answered

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#1668]
I have used baresip successfully in the past. I installed the latest version on a new install of Fedora 35. When I call out and the call is answered baresip simply hangs. "killall baresip" won't kill it. It requires "kill -9 <PID>" to kill it. Running it within gdb didn't help as gdb hangs as well. There are no clues in the system logs.
I imported an older version of baresip and it's libraries and it can call out and answer with twoway audio. Both versions used the same config.
Wireshark shows incoming rtp but no outgoing.
Fedora 35 uses pipewire and wireplumber by default.
I am open to suggestions on diagnosing the problem.

[baresip-hang.txt](https://github.com/baresip/baresip/files/7614891/baresip-hang.txt)

**Comment by sreimers** [comment]
I could reproduce this and connect with `gdb -q baresip PID`

```gdb
#0  __futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=13858, futex_word=0x7f448ec63910) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f448ec63910, expected=13858, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128, cancel=cancel@entry=true)
    at futex-internal.c:87
#2  0x00007f44a41297df in __GI___futex_abstimed_wait_cancelable64
    (futex_word=futex_word@entry=0x7f448ec63910, expected=<optimized out>, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128) at futex-internal.c:139
#3  0x00007f44a412e5f4 in __pthread_clockjoin_ex (threadid=139932429858368, thread_return=0x0, clockid=0, abstime=0x0, block=<optimized out>) at pthread_join_common.c:105
#4  0x0000000000467d1c in auplay_destructor (arg=0x168ef58) at modules/alsa/alsa_play.c:42
#5  0x00000000004bd34b in mem_deref (data=0x168ef58) at src/mem/mem.c:321
#6  0x0000000000422894 in stop_rx (rx=0x168a488) at src/audio.c:323
#7  0x000000000042633c in audio_stop (a=0x168a168) at src/audio.c:1979
#8  0x00000000004291ea in call_stream_stop (call=0x166df38) at src/call.c:215
#9  0x0000000000429861 in call_destructor (arg=0x166df38) at src/call.c:391
#10 0x00000000004bd34b in mem_deref (data=0x166df38) at src/mem/mem.c:321
#11 0x00000000004b54c2 in list_flush (list=0x14bf3a8) at src/list/list.c:51
#12 0x000000000043f804 in ua_destroy (ua=0x14bf368) at src/ua.c:322
#13 0x00000000004437d8 in ua_stop_all (forced=false) at src/uag.c:624
#14 0x0000000000427c31 in cmd_quit (pf=0x513830 <pf_stderr>, unused=0x7fff7acebd30) at src/baresip.c:43
#15 0x000000000042f5ac in cmd_process (commands=0x14fd9b8, ctxp=0x513bb8 <baresip+216>, key=113 'q', pf=0x513830 <pf_stderr>, data=0x0) at src/cmd.c:566
#16 0x00000000004446b2 in ui_input_key (uis=0x513ba8 <baresip+200>, key=113 'q', pf=0x513830 <pf_stderr>) at src/ui.c:66
#17 0x0000000000473fe8 in report_key (ui=0x1668518, key=113 'q') at modules/stdio/stdio.c:66
#18 0x000000000047407e in ui_fd_handler (flags=1, arg=0x1668518) at modules/stdio/stdio.c:90
#19 0x00000000004bc426 in fd_poll (re=0x513980 <global_re>) at src/main/main.c:877
#20 0x00000000004bc735 in re_main (signalh=0x448842 <signal_handler>) at src/main/main.c:1014
#21 0x0000000000448e1c in main (argc=1, argv=0x7fff7acec338) at src/main.c:302
```

So the pthread_join is hanging on destroy: https://github.com/baresip/baresip/blob/master/modules/alsa/alsa_play.c#L42

Maybe a race condition.

**Comment by sreimers** [comment]
Reverting this commit helps:

https://github.com/baresip/baresip/commit/768442014a9702f58dabbfb8e258d96b0ee453b4

**Comment by sreimers** [comment]
Can you try this PR: https://github.com/baresip/baresip/pull/1669

**Comment by robdyck** [comment]
With the changes applied outgoing calls are now working.
