### ISSUE TITLE
Regression: Using GTK3 UI 'Dial…' leads to segmentation fault with v2.9.0

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#2315]
Using GTK3 UI `Dial…` leads to segmentation fault (input phone number, press "Call", segmentation fault) with v2.9.0. Given this worked until (including) v2.8.2, this has been quite likely introduced commit 9a9c3eabc88098d4be67f555c68363f445fcc48f – @cspiel1?

Note: I'm using `gtk_clean_number yes`, if that matters.

Ah, and the phone number I put into is not a secret: `0800-1071023` (Vodafone Germany test number for phones and DTMF, only reachable from Vodafone customers). The backtrace also should not contain anything that I consider a secret (possibly some RFC 1918 IP addresses, username/password from a test environment).

**Comment by robert-scheck** [comment]
```
Program terminated with signal 11, Segmentation fault.
#0  re_regex (ptr=<optimized out>, len=3355183, expr=expr@entry=0x7f5cae982bb7 "sip:") at /usr/src/debug/re-2.9.0/src/fmt/regex.c:112
112				if (tolower(*ep) != tolower(*p)) {
```

**Comment by robert-scheck** [comment]
```
(gdb) bt full
#0  re_regex (ptr=<optimized out>, len=3355183, expr=expr@entry=0x7ff4edd39bb7 "sip:") at /usr/src/debug/re-2.9.0/src/fmt/regex.c:112
        __res = <error reading variable __res (Cannot access memory at address 0x3137303130303830)>
        chrv = {{min = 27 '\033', max = 255 '\377'}, {min = 1 '\001', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {
            min = 0 '\000', max = 0 '\000'}, {min = 27 '\033', max = 255 '\377'}, {min = 1 '\001', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 10 '\n', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', 
            max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 200 '\310', max = 239 '\357'}, {min = 59 ';', 
            max = 212 '\324'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 176 '\260', 
            max = 140 '\214'}, {min = 49 '1', max = 212 '\324'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 80 'P', max = 54 '6'}, {min = 142 '\216', max = 219 '\333'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', 
            max = 0 '\000'}, {min = 214 '\326', max = 76 'L'}, {min = 111 'o', max = 236 '\354'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 232 '\350', max = 239 '\357'}, {min = 59 ';', max = 212 '\324'}, {min = 244 '\364', 
            max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 176 '\260', max = 57 '9'}, {min = 142 '\216', max = 219 '\333'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 10 '\n', max = 0 '\000'}, {min = 0 '\000', 
            max = 0 '\000'}, {min = 10 '\n', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 140 '\214', max = 87 'W'}, {min = 102 'f', max = 236 '\354'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 10 '\n', max = 0 '\000'}, 
          {min = 0 '\000', max = 0 '\000'}, {min = 10 '\n', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 46 '.', max = 216 '\330'}, {min = 140 '\214', max = 237 '\355'}, {min = 244 '\364', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}}
        p = 0x3137303130303830 <Address 0x3137303130303830 out of bounds>
        ep = 0x7ff4edd39bb7 "sip:"
        fm = false
        range = false
        ec = false
        neg = false
        qesc = false
        n = 0
        ap = {{gp_offset = 24, fp_offset = 4294967295, overflow_arg_area = 0x7ff4db8e36d0, reg_save_area = 0x7ff4db8e3660}}
        eesc = <optimized out>
        l = 3355184
#1  0x00007ff4edd190a6 in account_uri_complete_strdup (uri=0x7ff4db8e3760, strp=0x7ff4db8e3760, acc=0x0) at /usr/src/debug/baresip-2.9.0/src/account.c:1775
        uri_is_ip = <optimized out>
        mb = 0x7ff4d43b82d0
        err = 0
        sa_addr = {u = {sa = {sa_family = 5360, sa_data = ":\324\364\177\000\000\000\000\000\000\000\000\000"}, in = {sin_family = 5360, sin_port = 54330, sin_addr = {s_addr = 32756}, sin_zero = "\000\000\000\000\000\000\000"}, in6 = {sin6_family = 5360, 
              sin6_port = 54330, sin6_flowinfo = 32756, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>}}, sin6_scope_id = 3762665320}, padding = "\360\024:\324\364\177", '\000' <repeats 18 times>, "h\267", <incomplete sequence \340>}, len = 32756}
        uridup = 0x7ff4e1fb07ea <gtk_entry_buffer_emit_inserted_text+26> "H\205\333t\034H\213;H\205\377t\005H;\at4H\211\306H\211\337\350yd\355\377\205\300u%H\203\304\bH\215\025\346l$"
        host = <optimized out>
        complete = <optimized out>
        c = <optimized out>
        trimmed = {p = 0x3137303130303830 <Address 0x3137303130303830 out of bounds>, l = 3355184}
#2  account_uri_complete_strdup (acc=0x0, strp=strp@entry=0x7ff4db8e3760, uri=uri@entry=0x7ff4d43b0080) at /usr/src/debug/baresip-2.9.0/src/account.c:1748
No locals.
#3  0x00007ff4e270e1e3 in gtk_mod_connect (mod=0x7ff4e29127e0 <mod_obj>, uri=0x7ff4d43b0080 "08001071023") at /usr/src/debug/baresip-2.9.0/modules/gtk/gtk_mod.c:780
        uric = 0x0
        err = 0
#4  0x00007ff4e270f6ad in dial_dialog_on_response (dialog=0x7ff4d4311170, response_id=<optimized out>, arg=0x7ff4d432d290) at /usr/src/debug/baresip-2.9.0/modules/gtk/dial_dialog.c:39
        dd = 0x7ff4d432d290
        uri = 0x7ff4d43b0080 "08001071023"
#5  0x00007ff4e0753eec in g_cclosure_marshal_VOID__INTv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x7ff4d4318cb0) at gmarshal.c:1200
        cc = <optimized out>
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = <optimized out>
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ff4db8e3a90, reg_save_area = 0x7ff4db8e39d0}}
#6  0x00007ff4e0751c47 in _g_closure_invoke_va (closure=closure@entry=0x7ff4d43aa9b0, return_value=return_value@entry=0x0, instance=instance@entry=0x7ff4d4311170, args=args@entry=0x7ff4db8e39b0, n_params=1, param_types=0x7ff4d4318cb0) at gclosure.c:867
        marshal = 0x7ff4e0753e90 <g_cclosure_marshal_VOID__INTv>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x7ff4d43aa990
        __FUNCTION__ = "_g_closure_invoke_va"
#7  0x00007ff4e076b6f7 in g_signal_emit_valist (instance=0x7ff4d4311170, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ff4db8e39b0) at gsignal.c:3301
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, 
              v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x7ff4db8e3ba0, instance = 0x7ff4d4311170, ihint = {signal_id = 220, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 140689508848320}
        signal_id = 220
        instance_type = 140689508848320
        emission_return = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, 
              v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = 0x7ff4d43aa9b0
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = 0x7ff4d43200c0
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ = "g_signal_emit_valist"
#8  0x00007ff4e076c37f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3448
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ff4db8e3a90, reg_save_area = 0x7ff4db8e39d0}}
#9  0x00007ff4e0751c47 in _g_closure_invoke_va (closure=closure@entry=0x7ff4d4306df0, return_value=return_value@entry=0x0, instance=instance@entry=0x7ff4d4319500, args=args@entry=0x7ff4db8e3c60, n_params=0, param_types=0x0) at gclosure.c:867
        marshal = 0x7ff4e0753a00 <g_cclosure_marshal_VOID__VOIDv>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x7ff4d4306dd0
        __FUNCTION__ = "_g_closure_invoke_va"
#10 0x00007ff4e076b6f7 in g_signal_emit_valist (instance=0x7ff4d4319500, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ff4db8e3c60) at gsignal.c:3301
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, 
              v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x7ff4d4319500, ihint = {signal_id = 224, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 140689508891856}
        signal_id = 224
        instance_type = 140689508891856
        emission_return = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, 
              v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = 0x7ff4d4306df0
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = 0x7ff4d432f470
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ = "g_signal_emit_valist"
#11 0x00007ff4e076c37f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3448
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ff4db8e3d40, reg_save_area = 0x7ff4db8e3c80}}
#12 0x00007ff4e1f2c9fe in button_activate_timeout (data=<optimized out>) at gtkbutton.c:1982
No locals.
#13 0x00007ff4e1b41598 in gdk_threads_dispatch (data=data@entry=0x7ff4d4172820) at gdk.c:743
        dispatch = 0x7ff4d4172820
        ret = 0
#14 0x00007ff4e0478b4d in g_timeout_dispatch (source=0x7ff4d43be550, callback=0x7ff4e1b41570 <gdk_threads_dispatch>, user_data=0x7ff4d4172820) at gmain.c:4648
        timeout_source = <optimized out>
        again = <optimized out>
#15 0x00007ff4e0478119 in g_main_dispatch (context=0x7ff4d4036a00) at gmain.c:3175
        dispatch = 0x7ff4e0478b30 <g_timeout_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x7ff4d4172820
        callback = 0x7ff4e1b41570 <gdk_threads_dispatch>
        cb_funcs = 0x7ff4e0740940 <g_source_callback_funcs>
        cb_data = 0x7ff4d43b2280
        need_destroy = <optimized out>
        source = 0x7ff4d43be550
        current = 0x7ff4d407c1b0
        i = 0
#16 g_main_context_dispatch (context=context@entry=0x7ff4d4036a00) at gmain.c:3828
No locals.
#17 0x00007ff4e0478478 in g_main_context_iterate (context=0x7ff4d4036a00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3901
        max_priority = 2147483647
        timeout = 187
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x7ff4d42464d0
#18 0x00007ff4e047874a in g_main_loop_run (loop=0x7ff4d4200810) at gmain.c:4097
        __FUNCTION__ = "g_main_loop_run"
#19 0x00007ff4e202e585 in gtk_main () at gtkmain.c:1323
        loop = 0x7ff4d4200810
#20 0x00007ff4e270cf0d in gtk_thread (arg=0x7ff4e29127e0 <mod_obj>) at /usr/src/debug/baresip-2.9.0/modules/gtk/gtk_mod.c:1088
        mod = 0x7ff4e29127e0 <mod_obj>
        app_menu = 0x7ff4d42f22a0
        item = 0x7ff4d42f8190
        err = 0x0
        le = <optimized out>
        theme = <optimized out>
#21 0x00007ff4ec9b5ea5 in start_thread (arg=0x7ff4db8e4700) at pthread_create.c:307
        __res = <optimized out>
        pd = 0x7ff4db8e4700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140689632282368, 759262387459079339, 0, 8392704, 0, 140689632282368, -765394224197649237, -765427043091727189}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#22 0x00007ff4ec6deb0d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
(gdb) 
```
