### ISSUE TITLE
baresip crash on Debian

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#3259]
While testing the telephone-event issue, I noticed that baresip (latest baresip and re) crashes when call is closed:
```
hread 1 "baresip" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ebbe93 in re_regex (ptr=<optimized out>, len=<optimized out>, 
    expr=expr@entry=0x7fffffffd920 "[ ]*[ \t\r\n]*scode[ \t\r\n]*=[ \t\r\n]*[~ \t\r\n ]+") at ./src/fmt/regex.c:161
161	./src/fmt/regex.c: No such file or directory.
(gdb) where full
#0  0x00007ffff7ebbe93 in re_regex
    (ptr=<optimized out>, len=<optimized out>, expr=expr@entry=0x7fffffffd920 "[ ]*[ \t\r\n]*scode[ \t\r\n]*=[ \t\r\n]*[~ \t\r\n ]+") at ./src/fmt/regex.c:161
        nmin = <optimized out>
        nmax = <optimized out>
        pl = 0x7fffffffd910
        esc = false
        nm = 0
        lpl = {p = 0x7ffff7fff000 <error: Cannot access memory at address 0x7ffff7fff000>, l = 0}
        quote = false
        chrv = {{min = 32 ' ', max = 32 ' '}, {min = 9 '\t', max = 9 '\t'}, {min = 13 '\r', max = 13 '\r'}, {min = 10 '\n', max = 10 '\n'}, {min = 79 'O', max = 183 '\267'}, {min = 235 '\353', max = 247 '\367'}, {min = 255 '\377', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 48 '0', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 48 '0', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 8 '\b', max = 217 '\331'}, {min = 255 '\377', max = 255 '\377'}, {min = 255 '\377', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 48 '0', max = 216 '\330'}, {min = 255 '\377', max = 255 '\377'}, {min = 255 '\377', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 164 '\244'}, {min = 74 'J', max = 174 '\256'}, {min = 119 'w', max = 86 '--Type <RET> for more, q to quit, c to continue without paging-- 
V'}, {min = 185 '\271', max = 68 'D'}, {min = 172 '\254', max = 153 '\231'}, {min = 252 '\374', max = 247 '\367'}, {min = 255 '\377', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 164 '\244'}, {min = 74 'J', max = 174 '\256'}, {min = 119 'w', max = 86 'V'}, {min = 185 '\271', max = 68 'D'}, {min = 48 '0', max = 177 '\261'}, {min = 121 'y', max = 85 'U'}, {min = 85 'U', max = 85 'U'}, {min = 0 '\000', max = 0 '\000'}, {min = 4 '\004', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 32 ' ', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 8 '\b', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 0 '\000'}, {min = 48 '0', max = 177 '\261'}, {min = 121 'y', max = 85 'U'}, {min = 85 'U', max = 85 'U'}, {min = 0 '\000', max = 0 '\000'}, {min = 0 '\000', max = 164 '\244'}, {min = 74 'J', max = 174 '\256'}, {min = 119 'w', max = 86 'V'}, {min = 185 '\271', max = 68 'D'}, {min = 208 '\320', max = 216 '\330'}, {min = 255 '\377', max = 255 '\377'}, {min = 255 '\377', max = 127 '\177'}, {min = 0 '\000', max = 0 '\000'}, {min = 16 '\020', max = 176 '\260'}, {min = 108 'l', max = 85 'U'}, {min = 85 'U', max = 85 'U'}, {min = 0 '\000', max = 0 '\000'}}
        p = 0x7ffff7fff000 <error: Cannot access memory at address 0x7ffff7fff000>
        ep = 0x7fffffffd923 "*[ \t\r\n]*scode[ \t\r\n]*=[ \t\r\n]*[~ \t\r\n ]+"
--Type <RET> for more, q to quit, c to continue without paging--
        fm = false
        range = false
        ec = <optimized out>
        neg = false
        qesc = false
        n = 1
        ap = {{gp_offset = 32, fp_offset = 1152996983, overflow_arg_area = 0x7fffffffd900, reg_save_area = 0x7fffffffd890}}
        eesc = <optimized out>
        l = 93824992038172
#1  0x00007ffff7ebba40 in fmt_param_sep_get
    (pl=0x7fffffffd9f0, pname=<optimized out>, sep=<optimized out>, val=0x7fffffffda00) at ./src/fmt/prm.c:63
        semi = {p = 0x7ffff7ffefff "", l = 0}
        expr = "[ ]*[ \t\r\n]*scode[ \t\r\n]*=[ \t\r\n]*[~ \t\r\n ]+\000@\251\300\377\177\000\000\020\310qUUU\000\000\300 \374\367\377\177\000\000\220\331\377\377", '\000' <repeats 28 times>, "  \000\000\000\000\000\000\000\244J\256wV\271DX\000\000\000\000\000\000\000\240ɩ\300\377\177\000"
#2  0x00007fffc0a950fd in  ()
    at /usr/lib/x86_64-linux-gnu/baresip/modules/menu.so
#3  0x00007ffff7f72c05 in cmd_process ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /lib/x86_64-linux-gnu/libbaresip.so.19
#4  0x00007ffff7fbf358 in  ()
    at /usr/lib/x86_64-linux-gnu/baresip/modules/stdio.so
#5  0x00007ffff7ece51d in fd_poll (re=re@entry=0x55555555a2b0)
    at ./src/main/main.c:925
        fd = <optimized out>
        flags = <optimized out>
        to = <optimized out>
        i = 0
        n = 1
        nfds = 17
        err = 0
        fhs = <optimized out>
        rfds = {fds_bits = {0, 0, 0, 0, 2, 4952084337295795200, 0, 93824992256880, 140736425698000, 2590239, 0, 93824992244589, 0, 140737352805948, 140737352554112, 56}}
        wfds = {fds_bits = {40, 4952084337295795200, 140737488346112, 140737352807524, 206158430256, 140737488346272, 140737488346080, 4952084337295795200, 140737353914796, 93824992256880, 140737353914796, 93824992256880, 100, 93824992259112, 140737352750576, 140737351488505}}
        efds = {fds_bits = {2590, 140737352983345, 2590, 140737352883763, 140737--Type <RET> for more, q to quit, c to continue without paging--
353914796, 93824992256880, 93824992242176, 93824992256700, 0, 140737351488505, 614182913509, 140737352983345, 2590, 317023445, 140737352750576, 4952084337295795200}}
#6  0x00007ffff7ecf485 in re_main (signalh=0x555555556a00)
    at ./src/main/main.c:1064
        re = <optimized out>
        err = <optimized out>
#7  0x000055555555676a in  ()
#8  0x00007ffff7cd124a in __libc_start_call_main
    (main=main@entry=0x555555556330, argc=argc@entry=2, argv=argv@entry=0x7fffffffe028) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737488347176, 7256476555969010410, 0, 140737488347200, 93824992251304, 140737354125344, -7256476557030483222, -7256493752028783894}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffe028, 0x7fffffffe028}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8152}}}
        not_first_call = <optimized out>
#9  0x00007ffff7cd1305 in __libc_start_main_impl
    (main=0x555555556330, argc=2, argv=0x7fffffffe028, init=<optimized out>, fin--Type <RET> for more, q to quit, c to continue without paging--
i=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe018)
    at ../csu/libc-start.c:360
#10 0x0000555555556901 in  ()
```

**Comment by alfredh** [comment]
I got the same crash on macOS 13 when pressing `h` for hangup:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x100050000)
  * frame #0: 0x0000000100288210 libre.28.dylib`re_regex(ptr="", len=435546661, expr="[ ]*[ \t\r\n]*scode[ \t\r\n]*=[ \t\r\n]*[~ \t\r\n ]+") at regex.c:176:38
    frame #1: 0x0000000100287c84 libre.28.dylib`fmt_param_sep_get(pl=0x000000016fdfecd8, pname="scode", sep=' ', val=0x000000016fdfecc8) at prm.c:63:6
    frame #2: 0x0000000100952884 menu.so`cmd_hangup(pf=0x00000001003a4030, arg=0x000000016fdfed50) at static_menu.c:810:2
    frame #3: 0x00000001000ee96c libbaresip.19.dylib`cmd_process(commands=0x0000600003904dc0, ctxp=0x0000000100124a80, key='\e', pf=0x00000001003a4030, data=0x0000000000000000) at cmd.c:566:10
    frame #4: 0x0000000100110940 libbaresip.19.dylib`ui_input_key(uis=0x0000000100124a70, key='\e', pf=0x00000001003a4030) at ui.c:66:8
    frame #5: 0x000000010039fdc8 stdio.so`report_key(ui=0x00000001004468d0, key='\e') at stdio.c:67:2
    frame #6: 0x000000010039fc5c stdio.so`ui_fd_handler(flags=1, arg=0x00000001004468d0) at stdio.c:91:2
    frame #7: 0x00000001002a4894 libre.28.dylib`fd_poll(re=0x0000000100504320) at main.c:925:4
    frame #8: 0x00000001002a3e24 libre.28.dylib`re_main(signalh=(baresip`signal_handler at main.c:23)) at main.c:1064:9
    frame #9: 0x000000010000365c baresip`main(argc=2, argv=0x000000016fdff678) at main.c:327:8
    frame #10: 0x0000000182d9ffd8 dyld`start + 2412
```

**Comment by sreimers** [comment]
Looks like introduced by https://github.com/baresip/baresip/pull/3238

CC: @maximilianfridrich

**Comment by alfredh** [comment]
perhaps this patch can help:

```diff
diff --git a/modules/menu/static_menu.c b/modules/menu/static_menu.c
index ebeb8541..59e1c1ad 100644
--- a/modules/menu/static_menu.c
+++ b/modules/menu/static_menu.c
@@ -795,7 +795,7 @@ static int cmd_hangup(struct re_printf *pf, void *arg)
        int err;
        uint32_t scode = 0;
        char *reason = NULL;
-       struct pl params;
+       struct pl params = PL_INIT;
        struct pl pl = PL_INIT;
        struct ua *ua = NULL;
        struct call *call = NULL;
```

**Comment by juha-h** [comment]
Yes, it helped.

**Comment by maximilianfridrich** [comment]
Sorry about that. Fixed in #3264.
